# Generated by Django 5.0.6 on 2024-06-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_otpcode_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpcode',
            name='user',
        ),
        migrations.AddField(
            model_name='otpcode',
            name='email',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
