# Generated by Django 5.0.6 on 2024-06-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0006_remove_otpcode_user_otpcode_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('pptx', models.FileField(upload_to='pptx/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
