# Generated by Django 5.0.6 on 2024-06-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0007_studymaterials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studymaterials',
            name='description',
        ),
        migrations.RemoveField(
            model_name='studymaterials',
            name='subject',
        ),
    ]
