# Generated by Django 5.0.6 on 2024-07-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0010_studymaterials_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterials',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
