# Generated by Django 5.0.6 on 2024-07-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0012_shareproblems'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareproblems',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shareproblems',
            name='tags',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
    ]
