# Generated by Django 5.0.6 on 2024-07-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0013_shareproblems_description_shareproblems_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareproblems',
            name='code',
            field=models.TextField(max_length=255),
        ),
    ]
