# Generated by Django 3.2.25 on 2024-08-23 04:50

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0014_alter_shareproblems_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareproblems',
            name='title',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255)),
        ),
    ]
