# Generated by Django 3.2.25 on 2024-08-23 05:00

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0016_alter_shareproblems_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareproblems',
            name='tags',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255)),
        ),
    ]
