# Generated by Django 3.2.25 on 2024-10-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0019_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree',
            name='degree',
        ),
        migrations.AddField(
            model_name='degree',
            name='degree1',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='degree',
            name='degree2',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='degree',
            name='degree3',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='degree',
            name='servo_name',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
