# Generated by Django 3.2.25 on 2024-10-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0020_auto_20241008_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='servo_name',
            field=models.CharField(default='servo', max_length=100),
        ),
    ]
